/**
 * This file was generated by sqlenumgen maven plugin
 */
package de.enlightened.sqlenum;

import javax.annotation.Generated;

/**
 * Enum representing testEnum
 *
 * (This class was generated by sqlenumgen maven plugin)
 */
@Generated(
    value = {
        "https://github.com/McNetic/sqlenumgen",
        "sqlenumgen version:0.1.0",
    },
    date = "2016-09-30T23:27:40.391Z",
    comments = "This class was generated by sqlenumgen maven plugin"
)
public enum testEnum {
  name1(1, "name1"),
  name2(2, "name2");

  private final Integer ID;

  private final String NAME;

  private testEnum(final Integer ID, final String NAME) {
    this.ID = ID;
    this.NAME = NAME;
  }

  public final Integer getID() {
    return this.ID;
  }

  public final String getNAME() {
    return this.NAME;
  }
}
